apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sealio-corp
  description: The sealio-corp organization
  links:
    - url: http://seal.io
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: SealIO Corp
    email: info@sealio.net
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./platform-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
