apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-c
  description: Team C
spec:
  type: team
  profile:
    displayName: Team C
    email: team-c@sealio.net
    picture: https://avatars.dicebear.com/api/identicon/team-c@example.com.svg?background=%23fff&margin=25
  parent: boxoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lawrence.li
spec:
  profile:
    displayName: Lawrence Li
    email: lawrence.li@sealio.net
    picture: https://avatars.dicebear.com/api/avataaars/calum-leavy@example.com.svg?background=%23fff
  memberOf: [team-c]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: frank.mai
spec:
  profile:
    displayName: Frank Mai
    email: frank.mai@sealio.net
    picture: https://avatars.dicebear.com/api/avataaars/frank-tiernan@example.com.svg?background=%23fff
  memberOf: [team-c]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: can.chen
spec:
  profile:
    displayName: Can Chen
    email: can.chen@sealio.net
    picture: https://avatars.dicebear.com/api/avataaars/peadar-macmahon@example.com.svg?background=%23fff
  memberOf: [team-c]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jialin.kuang
spec:
  profile:
    displayName: Jialin Kuang
    email: jialin.kuang@sealio.net
    picture: https://avatars.dicebear.com/api/avataaars/sarah-gilroy@example.com.svg?background=%23fff
  memberOf: [team-c]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: michelle.feng
spec:
  profile:
    displayName: Michelle Feng
    email: michelle.feng@sealio.net
    picture: https://avatars.dicebear.com/api/avataaars/tara-macgovern@example.com.svg?background=%23fff
  memberOf: [team-c]
